sudo: false
language: d
d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - ldc-beta
  - ldc

os:
  - linux
# TODO, some bug in OSX for the server that causes it to fail
#  - osx

env:
  - BUILD=
  - BUILD=dub

script: ./.travis.sh
