name: CI
on: [push, pull_request]

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dc:
          - ldc-latest
          - dmd-latest
        arch:
          - x86_64
        include:
          # windows x86
          - os: windows-latest
            arch: x86
            dc: ldc-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup D
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build
        run: |
          dub build --build=release --config=client --arch=${{ matrix.arch }}
          dub build --build=release --config=server --arch=${{ matrix.arch }}

      - name: Linux Tests
        if: contains(matrix.os, 'ubuntu')
        run: |
          ./run_tests.sh
        working-directory: tests
        shell: bash

      - name: Windows and MacOS Tests
        if: contains(matrix.os, 'windows') || contains(matrix.os, 'macos')
        run: |
          ./run_tests.sh
        working-directory: tests
        shell: bash
        continue-on-error: true
